export const REGISTER_INIT = 'REGISTER_INIT'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS'
export const REGISTER_REQUEST_ERROR = 'REGISTER_REQUEST_ERROR'

export const LOGIN_INIT = 'LOGIN_INIT'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_REQUEST_ERROR = 'LOGIN_REQUEST_ERROR'

export const AUTHORIZED = 'AUTHORIZED'

export const LOGOUT_INIT = 'LOGOUT_INIT'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
