const AUTH = 'AUTH'
export default AUTH
export const AUTHORIZATION = 'AUTHORIZATION'
export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED'
export const AUTH_LOGIN_SUCCESSFUL = 'AUTH_LOGIN_SUCCEEDED'
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED'
export const AUTH_REGISTER_REQUESTED = 'AUTH_REGISTER_REQUESTED'
