export const CITY_BROWSE_INIT = 'CITY_BROWSE_INIT'
export const CITY_BROWSE_REQUEST = 'CITY_BROWSE_REQUEST'
export const CITY_BROWSE_REQUEST_SUCCESS = 'CITY_BROWSE_REQUEST_SUCCESS'
export const CITY_BROWSE_REQUEST_ERROR = 'CITY_BROWSE_REQUEST_ERROR'
