export const EMPLOYEE_BROWSE_INIT = 'EMPLOYEE_BROWSE_INIT'
export const EMPLOYEE_BROWSE_REQUEST = 'EMPLOYEE_BROWSE_REQUEST'
export const EMPLOYEE_BROWSE_REQUEST_SUCCESS = 'EMPLOYEE_BROWSE_REQUEST_SUCCESS'
export const EMPLOYEE_BROWSE_REQUEST_ERROR = 'EMPLOYEE_BROWSE_REQUEST_ERROR'
