export const SHOP_BROWSE_INIT = 'SHOP_BROWSE_INIT'
export const SHOP_BROWSE_REQUEST = 'SHOP_BROWSE_REQUEST'
export const SHOP_BROWSE_REQUEST_SUCCESS = 'SHOP_BROWSE_REQUEST_SUCCESS'
export const SHOP_BROWSE_REQUEST_ERROR = 'SHOP_BROWSE_REQUEST_ERROR'

export const SHOP_BROWSE_CLEAR = 'SHOP_BROWSE_CLEAR'
