export const TASK_BROWSE_INIT = 'TASK_BROWSE_INIT'
export const TASK_BROWSE_REQUEST = 'TASK_BROWSE_REQUEST'
export const TASK_BROWSE_REQUEST_SUCCESS = 'TASK_BROWSE_REQUEST_SUCCESS'
export const TASK_BROWSE_REQUEST_ERROR = 'TASK_BROWSE_REQUEST_ERROR'
export const TASK_BROWSE_CHANGE_PAGE = 'TASK_BROWSE_CHANGE_PAGE'

export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST'
export const TASK_ADD_REQUEST_SUCCESS = 'TASK_ADD_REQUEST_SUCCESS'
export const TASK_ADD_REQUEST_ERROR = 'TASK_ADD_REQUEST_ERROR'

export const TASK_READ_INIT = 'TASK_READ_INIT'
export const TASK_READ_REQUEST = 'TASK_READ_REQUEST'
export const TASK_READ_REQUEST_SUCCESS = 'TASK_READ_REQUEST_SUCCESS'
export const TASK_READ_REQUEST_ERROR = 'TASK_READ_REQUEST_ERROR'

export const TASK_EDIT_INIT = 'TASK_EDIT_INIT'
export const TASK_EDIT_REQUEST = 'TASK_EDIT_REQUEST'
export const TASK_EDIT_REQUEST_SUCCESS = 'TASK_EDIT_REQUEST_SUCCESS'
export const TASK_EDIT_REQUEST_ERROR = 'TASK_EDIT_REQUEST_ERROR'

export const TASK_STATUS_INIT = 'TASK_STATUS_INIT'
export const TASK_STATUS_REQUEST = 'TASK_STATUS_REQUEST'
export const TASK_STATUS_REQUEST_SUCCESS = 'TASK_STATUS_REQUEST_SUCCESS'
export const TASK_STATUS_REQUEST_ERROR = 'TASK_STATUS_REQUEST_ERROR'
