export const TASK_BROWSE_INIT = 'TASK_BROWSE_INIT'
export const TASK_BROWSE_REQUEST = 'TASK_BROWSE_REQUEST'
export const TASK_BROWSE_REQUEST_SUCCESS = 'TASK_BROWSE_REQUEST_SUCCESS'
export const TASK_BROWSE_REQUEST_ERROR = 'TASK_BROWSE_REQUEST_ERROR'
export const TASK_BROWSE_CHANGE_PAGE = 'TASK_BROWSE_CHANGE_PAGE'

export const TASK_ADD_REQUEST = 'TASK_ADD_REQUEST'

export const TASK_INSTANCE_INIT = 'TASK_INSTANCE_INIT'
export const TASK_INSTANCE_REQUEST = 'TASK_INSTANCE_REQUEST'
export const TASK_INSTANCE_REQUEST_SUCCESS = 'TASK_INSTANCE_REQUEST_SUCCESS'
export const TASK_INSTANCE_REQUEST_ERROR = 'TASK_INSTANCE_REQUEST_ERROR'
