export const VERIFICATION_BROWSE_INIT = 'VERIFICATION_BROWSE_INIT'
export const VERIFICATION_BROWSE_REQUEST = 'VERIFICATION_BROWSE_REQUEST'
export const VERIFICATION_BROWSE_REQUEST_SUCCESS = 'VERIFICATION_BROWSE_REQUEST_SUCCESS'
export const VERIFICATION_BROWSE_REQUEST_ERROR = 'VERIFICATION_BROWSE_REQUEST_ERROR'
