export const VIOLATION_BROWSE_INIT = 'VIOLATION_BROWSE_INIT'
export const VIOLATION_BROWSE_REQUEST = 'VIOLATION_BROWSE_REQUEST'
export const VIOLATION_BROWSE_REQUEST_SUCCESS = 'VIOLATION_BROWSE_REQUEST_SUCCESS'
export const VIOLATION_BROWSE_REQUEST_ERROR = 'VIOLATION_BROWSE_REQUEST_ERROR'
